app:
  telegram-token: 6408299235:AAGwuJRMjIBpZi8zUOXM2TjZoPREsEhrNB0

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
